### ekf config file ###
ekf_filter_node:
    ros__parameters:

        frequency: 30.0

        sensor_timeout: 0.1

        two_d_mode: false

        transform_time_offset: 0.0

        transform_timeout: 0.0

        print_diagnostics: true

        debug: false

        # Defaults to "robot_localization_debug.txt" if unspecified. Please specify the full path.
        #debug_out_file: /path/to/debug/file.txt

        # Whether we'll allow old measurements to cause a re-publication of the updated state
        permit_corrected_publication: false

        # Whether to publish the acceleration state. Defaults to false if unspecified.
        publish_acceleration: false

        # Whether to broadcast the transformation over the /tf topic. Defaults to true if unspecified.
        publish_tf: true


        #map_frame: map              # Defaults to "map" if unspecified
        odom_frame: odom            # Defaults to "odom" if unspecified
        base_link_frame: base_link  # Defaults to "base_link" if unspecified
        world_frame: odom           # Defaults to the value of odom_frame if unspecified


        odom0: antonio_odom

 
        odom0_config: [true,  true,  false,
                       false, false, false,
                       false, false, false,
                       false, false, true,
                       false, false, false]


       #odom0: /antonio_odom
       #odom0_config: [true,  true,  false,
       #               false, false, true,
       #               false, false, false,
       #               false, false, false,
       #               false, false, false]
       ##odom0_differential: true
       #odom0_queue_size: 2
       ##odom0_relative: true

      # imu0: /imu/data
      # imu0_config: [false, false, false,       #       X,      Y,       Z
      #               true,  true,  true,        #       roll,   pitch,   yaw    
      #               false, false, false,       #       X_v,    Y_v,     Z_v 
      #               false, false, true,        #       roll_v, pitch_v, yaw_v  
      #               false, false, false]       #       X_acc,  Y_acc,   Z_acc
      # imu0_relative: true
      # #imu0_differential: true
      # imu0_queue_size: 10
        #imu0_remove_gravitational_acceleration: true

        #pose0: ccd_Z
        #pose0_config: [false,  false,  true,
        #               false, false, false,
        #               false, false, false,
        #               false, false, false,
        #               false, false, false]
        #pose0_differential: false
        #pose0_relative: true
        #pose0_queue_size: 5
        #pose0_rejection_threshold: 2.0  # Note the difference in parameter name
        #pose0_nodelay: false

        

